###########QSPI###################
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CONFIG_MODE SPIx8 [current_design]
###########BIT###################
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 85.0 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pulldown [current_design]
set_property BITSTREAM.CONFIG.PERSIST Yes [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]

###########PIN###################
set_property PACKAGE_PIN T19 [get_ports FPGA_PCIE_PERST_N]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_PCIE_PERST_N]

#set_property IOSTANDARD LVCMOS18 [get_ports aeskeyfinder_active_0]

set_property IOSTANDARD LVCMOS18 [get_ports mdio_rtl_0_mdc]
set_property IOSTANDARD LVCMOS18 [get_ports mdio_rtl_0_mdio_io]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rtl_0_rx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rtl_0_rxc]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rtl_0_tx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rtl_0_txc]

#LED
#set_property PACKAGE_PIN J12 [get_ports {GPIO_0_tri_o[0]}]
#set_property PACKAGE_PIN H14 [get_ports {GPIO_0_tri_o[1]}]
#set_property PACKAGE_PIN F13 [get_ports {GPIO_0_tri_o[2]}]
#set_property PACKAGE_PIN H12 [get_ports {GPIO_0_tri_o[3]}]

#set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_o[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_o[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_o[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_o[3]}]

#set_property PACKAGE_PIN H14 [get_ports user_lnk_up]
#set_property IOSTANDARD LVCMOS33 [get_ports user_lnk_up]


set_property PACKAGE_PIN H12 [get_ports {dout_0[0]}]
set_property PACKAGE_PIN F13 [get_ports user_lnk_up_0]
set_property PACKAGE_PIN H14 [get_ports aeskeyfinder_active_0]
set_property PACKAGE_PIN J12 [get_ports interrupt_out_0]
set_property IOSTANDARD LVCMOS18 [get_ports aeskeyfinder_active_0]
set_property IOSTANDARD LVCMOS18 [get_ports {dout_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports interrupt_out_0]
set_property IOSTANDARD LVCMOS18 [get_ports user_lnk_up_0]


#set_property IOSTANDARD LVCMOS18 [get_ports user_lnk_up_0]
set_property PACKAGE_PIN V7 [get_ports {PCIE_CLK_clk_p[0]}]
set_property PACKAGE_PIN K22 [get_ports {CLK_IN1_D_0_clk_p[0]}]
set_property PACKAGE_PIN K23 [get_ports {CLK_IN1_D_0_clk_n[0]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {CLK_IN1_D_0_clk_p[0]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {CLK_IN1_D_0_clk_n[0]}]
#create_clock -period 5.000 -name clk_200MHz -waveform {0.000 2.500} [get_ports {CLK_IN1_D_0_clk_p[0]}]


set_property PACKAGE_PIN V19 [get_ports {rgmii_rtl_0_rd[0]}]
set_property PACKAGE_PIN P20 [get_ports {rgmii_rtl_0_rd[1]}]
set_property PACKAGE_PIN P21 [get_ports {rgmii_rtl_0_rd[2]}]
set_property PACKAGE_PIN R22 [get_ports {rgmii_rtl_0_rd[3]}]
set_property PACKAGE_PIN P19 [get_ports {rgmii_rtl_0_td[3]}]
set_property PACKAGE_PIN N19 [get_ports {rgmii_rtl_0_td[2]}]
set_property PACKAGE_PIN V22 [get_ports {rgmii_rtl_0_td[1]}]
set_property PACKAGE_PIN V21 [get_ports {rgmii_rtl_0_td[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_rd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_rd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_rd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_rd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_td[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_td[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_td[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rtl_0_td[0]}]

set_property PACKAGE_PIN N26 [get_ports mdio_rtl_0_mdc]
set_property PACKAGE_PIN U19 [get_ports mdio_rtl_0_mdio_io]
set_property PACKAGE_PIN R23 [get_ports rgmii_rtl_0_rx_ctl]
set_property PACKAGE_PIN R26 [get_ports rgmii_rtl_0_tx_ctl]
set_property PACKAGE_PIN R25 [get_ports rgmii_rtl_0_txc]
set_property PACKAGE_PIN U21 [get_ports rgmii_rtl_0_rxc]

set_property PACKAGE_PIN N22 [get_ports {reset_rtl_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {reset_rtl_0[0]}]


create_clock -period 10.000 -name {PCIE_CLK_clk_p[0]} -waveform {0.000 5.000} [get_ports {PCIE_CLK_clk_p[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rxc_ibuf_i/O]
set_property UNAVAILABLE_DURING_CALIBRATION true [get_ports mdio_rtl_0_mdio_io]



set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[0].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[0].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[1].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[1].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[2].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[2].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[3].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[3].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[0].rgmii_txd_obuf_i}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[1].rgmii_txd_obuf_i}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[2].rgmii_txd_obuf_i}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[3].rgmii_txd_obuf_i}]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rx_ctl_ibuf_i/IBUFCTRL_INST]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rx_ctl_ibuf_i/INBUF_INST]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rxc_ibuf_i/IBUFCTRL_INST]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rxc_ibuf_i/INBUF_INST]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_tx_ctl_obuf_i]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_txc_obuf_i]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells mdio_rtl_0_mdio_iobuf/IBUFCTRL_INST]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells mdio_rtl_0_mdio_iobuf/INBUF_INST]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells mdio_rtl_0_mdio_iobuf/OBUFT]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells mdio_rtl_0_mdc_OBUF_inst]
set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells {reset_rtl_0_OBUF[0]_inst}]
set_property HD.TANDEM_IP_PBLOCK Stage1_Config_IO [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/bd_929b_mac_0_core/man_block.managen/mdio_enabled.phy/mdio_tristate_reg]

set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[0].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[0].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[1].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[1].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[2].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[2].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[3].rgmii_rxd_ibuf_i/IBUFCTRL_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/ibuf_data[3].rgmii_rxd_ibuf_i/INBUF_INST}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[0].rgmii_txd_obuf_i}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[1].rgmii_txd_obuf_i}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[2].rgmii_txd_obuf_i}]
set_property HD.TANDEM 1 [get_cells {design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/obuf_data[3].rgmii_txd_obuf_i}]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rx_ctl_ibuf_i/IBUFCTRL_INST]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rx_ctl_ibuf_i/INBUF_INST]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rxc_ibuf_i/IBUFCTRL_INST]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_rxc_ibuf_i/INBUF_INST]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_tx_ctl_obuf_i]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/rgmii_interface/rgmii_txc_obuf_i]
set_property HD.TANDEM 1 [get_cells mdio_rtl_0_mdio_iobuf/IBUFCTRL_INST]
set_property HD.TANDEM 1 [get_cells mdio_rtl_0_mdio_iobuf/INBUF_INST]
set_property HD.TANDEM 1 [get_cells mdio_rtl_0_mdio_iobuf/OBUFT]
set_property HD.TANDEM 1 [get_cells mdio_rtl_0_mdc_OBUF_inst]
set_property HD.TANDEM 1 [get_cells {reset_rtl_0_OBUF[0]_inst}]
set_property HD.TANDEM 1 [get_cells design_1_i/axi_ethernet_0/inst/mac/inst/tri_mode_ethernet_mac_i/bd_929b_mac_0_core/man_block.managen/mdio_enabled.phy/mdio_tristate_reg]


set_property LOC BITSLICE_CONTROL_X0Y15 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_rep_0]
set_property LOC BITSLICE_CONTROL_X0Y14 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_rep_3]
set_property LOC BITSLICE_CONTROL_X0Y13 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_rep_1]
set_property LOC BITSLICE_CONTROL_X0Y9 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_rep_2]
set_property LOC BITSLICE_CONTROL_X0Y8 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i]
set_property LOC SLICE_X0Y89 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND*]

set_property HD.TANDEM_IP_PBLOCK Stage1_IO [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i*]
set_property HD.TANDEM_IP_PBLOCK Stage1_Config_IO [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND*]
set_property HD.TANDEM 1 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i*]
set_property HD.TANDEM 1 [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND*]

set_property DONT_TOUCH TRUE [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i*]
set_property DONT_TOUCH TRUE [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND*]
set_property DONT_TOUCH TRUE [get_nets -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i*]

#set_property lock_pins {I0:A5 I1:A1} [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND_0]
#set_property lock_pins {I0:A3 I1:A1} [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND_1]
#set_property lock_pins {I0:A5 I1:A2} [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND_2]
#set_property lock_pins {I0:A4 I1:A1} [get_cells -hierarchical tri_mode_ethernet_mac_idelayctrl_common_i_TOP_AND_3]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
