name: Claim1 KR260

on:
  workflow_dispatch:
 
jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pwd
          cd claim/claim1/
          ./run.sh KR260
          # cd fpga/KR260/
          # vivado -mode batch -source build.tcl
          wait
          cat KR260_Periodic-AESKeyFinder/KR260_Periodic-AESKeyFinder.runs/impl_1/design_1_wrapper_utilization_placed.rpt

