name: Claim1 AXKU3

on:
  workflow_dispatch:
 
jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pwd
          cd fpga/AXKU3/
          vivado -mode batch -source build.tcl
          wait
          cat AXKU3_Periodic-AESKeyFinder/AXKU3_Periodic-AESKeyFinder.runs/impl_1/design_1_wrapper_utilization_placed.rpt

