name: install

on:
  workflow_dispatch:
 
jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pwd
          ./install.sh
          wait

